language: python
cache: pip
python:
  - 2.7
  - 3.5
install:
  - make dev install
script:
  - nosetests -w trump_net -c etc/tests.cfg --with-coverage --cover-package=trump_net
after_success:
  - coveralls --rcfile=.coveragerc
