# -*- coding: utf-8 -*-
# trump-net (c) Ian Dennis Miller

from situation import Person


donald_trump = Person.create(name="Donald Trump")
donald_trump_jr = Person.create(name="Donald Trump, Jr.")
fred_trump = Person.create(name="Fred Trump")
fred_trump_jr = Person.create(name="Fred Trump, Jr.")
ivana_trump = Person.create(name="Ivana Trump")
ivanka_trump = Person.create(name="Ivanka Trump")
eric_trump = Person.create(name="Eric Trump")
tiffany_trump = Person.create(name="Tiffany Trump")
barron_trump = Person.create(name="Barron Trump")
marla_maples = Person.create(name="Marla Maples")
melania_trump = Person.create(name="Melania Trump")
jared_kushner = Person.create(name="Jared Kushner")
charles_kushner = Person.create(name="Charles Kushner")
paul_manafort = Person.create(name="Paul Manafort")
steve_bannon = Person.create(name="Steve Bannon")
roger_stone = Person.create(name="Roger Stone")
kelly_anne_conway = Person.create(name="Kelly Anne Conway")
robert_mercer = Person.create(name="Robert Mercer")
rebekah_mercer = Person.create(name="Rebekah Mercer")
natalia_veselnetskaya = Person.create(name="Natalia Veselnetskaya")
milo_yiannopoulos = Person.create(name="Milo Yiannopoulos")
dmitry_rybolovlev = Person.create(name="Dmitry Rybolovlev")
artem_chaika = Person.create(name="Artem Chaika")
igor_chaika = Person.create(name="Igor Chaika")
yuri_chaika = Person.create(name="Yuri Chaika")
rob_goldstone = Person.create(name="Rob Goldstone")
aras_agalrov = Person.create(name="Aras Agalrov")
emin_agalrov = Person.create(name="Emin Agalrov")
dana_rohrbacher = Person.create(name="Dana Rohrbacher")
